# Adaugă noile controlere pentru brațul drept
right_shoulder_roll_controller:
  type: effort_controllers/JointPositionController
  joint: right_shoulder_roll
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_shoulder_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: right_shoulder_pitch
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_elbow_controller:
  type: effort_controllers/JointPositionController
  joint: right_elbow
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_wrist_controller:
  type: effort_controllers/JointPositionController
  joint: right_wrist
  pid: {p: 50.0, i: 0.01, d: 5.0}