<?xml version="1.0"?>
<robot name="simple_humanoid" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Materiale -->
  <material name="green">
    <color rgba="0 1 0 1"/> <!-- verde -->
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/> <!-- roșu -->
  </material>
  <material name="blue">
    <color rgba="0 0 1 1"/> <!-- albastru -->
  </material>

  <!-- Dimensiuni simple -->
  <xacro:property name="torso_x" value="0.3" />
  <xacro:property name="torso_y" value="0.2" />
  <xacro:property name="torso_z" value="0.4" />
  
  <xacro:property name="pelvis_x" value="0.35" />
  <xacro:property name="pelvis_y" value="0.25" />
  <xacro:property name="pelvis_z" value="0.15" />
  
  <xacro:property name="thigh_z" value="0.4" />
  <xacro:property name="calf_z" value="0.4" />
  <xacro:property name="arm_z" value="0.3" />

  <!-- BASE LINK (pelvis) -->
  <link name="pelvis">
    <visual>
      <geometry>
        <box size="${pelvis_x} ${pelvis_y} ${pelvis_z}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${pelvis_x} ${pelvis_y} ${pelvis_z}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="3.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- TORSO -->
  <link name="torso">
    <visual>
      <geometry>
        <box size="${torso_x} ${torso_y} ${torso_z}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${torso_x} ${torso_y} ${torso_z}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="8.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="pelvis_to_torso" type="fixed">
    <parent link="pelvis"/>
    <child link="torso"/>
    <origin xyz="0 0 ${pelvis_z/2 + torso_z/2}" rpy="0 0 0"/>
  </joint>

  <!-- PICIOARE -->
  <!-- Picior stâng -->
  <link name="left_thigh">
    <visual>
      <geometry>
        <cylinder length="${thigh_z}" radius="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${thigh_z}" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_hip" type="fixed">
    <parent link="pelvis"/>
    <child link="left_thigh"/>
    <origin xyz="-${pelvis_x/4} 0 -${pelvis_z}" rpy="0 0 0"/>
  </joint>

  <link name="left_calf">
    <visual>
      <geometry>
        <cylinder length="${calf_z}" radius="0.04"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${calf_z}" radius="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_knee" type="fixed">
    <parent link="left_thigh"/>
    <child link="left_calf"/>
    <origin xyz="0 0 -${thigh_z/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="2.0" effort="5" velocity="1.0"/>
  </joint>

  <!-- Picior drept -->
  <link name="right_thigh">
    <visual>
      <geometry>
        <cylinder length="${thigh_z}" radius="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${thigh_z}" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_hip" type="fixed">
    <parent link="pelvis"/>
    <child link="right_thigh"/>
    <origin xyz="${pelvis_x/4} 0 -${pelvis_z}" rpy="0 0 0"/>
  </joint>

  <link name="right_calf">
    <visual>
      <geometry>
        <cylinder length="${calf_z}" radius="0.04"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${calf_z}" radius="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_knee" type="fixed">
  <parent link="right_thigh"/>
  <child link="right_calf"/>
  <origin xyz="0 0 -${thigh_z/2}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <limit lower="0" upper="2.0" effort="5" velocity="1.0"/>
  </joint>

  <!-- BRATE -->
  <!-- Braț stâng -->
  
  <link name="left_upper_arm">
    <visual>
      <geometry>
        <cylinder length="${arm_z}" radius="0.03"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${arm_z}" radius="0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <joint name="left_shoulder" type="revolute">
    <parent link="torso"/>
    <child link="left_upper_arm"/>
    <origin xyz="-${torso_x-0.1} 0 ${torso_z-0.325}" rpy="0 0.14 -0.05"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.0" upper="1.0" effort="5" velocity="1.0"/>
  </joint>

<link name="left_forearm">
  <visual>
    <!-- mută cilindrul astfel încât vârful să fie la cot (origine link) -->
    <origin xyz="0 0 -${arm_z/2}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${arm_z}" radius="0.025"/>
    </geometry>
    <material name="green"/>
  </visual>
  <collision>
    <!-- și pentru coliziune aceeași deplasare -->
    <origin xyz="0 0 -${arm_z/2}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${arm_z}" radius="0.025"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.8"/>
    <inertia ixx="0.004" ixy="0" ixz="0" iyy="0.004" iyz="0" izz="0.004"/>
  </inertial>
</link>

<joint name="left_elbow" type="revolute">
  <parent link="left_upper_arm"/>
  <child link="left_forearm"/>
  <!-- cotul la capătul inferior al brațului superior -->
  <origin xyz="0 0 -${arm_z/2}" rpy="0 0 0"/>
  <axis xyz="1 0 0"/>
  <limit lower="0" upper="2.0" effort="3" velocity="1.0"/>
</joint>

  <!-- Braț drept -->
  <link name="right_upper_arm">
    <visual>
      <geometry>
        <cylinder length="${arm_z}" radius="0.03"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${arm_z}" radius="0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <joint name="right_shoulder" type="fixed">
    <parent link="torso"/>
    <child link="right_upper_arm"/>
    <origin xyz="${torso_x-0.1} 0 ${torso_z-0.33}" rpy="0 -0.14 -0.05"/>

    <!-- <origin xyz="${torso_x/2} 0 ${torso_z/3}" rpy="0 0 0"/> -->
  </joint>

  <link name="right_forearm">
    <visual>
      <!-- mutăm cilindrul astfel încât să pornească din cot -->
      <origin xyz="0 0 -${arm_z/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_z}" radius="0.025"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <!-- și pentru coliziune la fel -->
      <origin xyz="0 0 -${arm_z/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_z}" radius="0.025"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <inertia ixx="0.4" ixy="0" ixz="0" iyy="0.4" iyz="0" izz="0.4"/>
    </inertial>
  </link>

  <joint name="right_elbow" type="revolute">
    <parent link="right_upper_arm"/>
    <child link="right_forearm"/>
    <!-- cotul la capătul inferior al brațului superior -->
    <origin xyz="0 0 -${arm_z/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="2.0" effort="3" velocity="1.0"/>
  </joint>
  <!-- CAP -->
  <link name="head">
    <visual>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="neck" type="fixed">
    <parent link="torso"/>
    <child link="head"/>
    <origin xyz="0 0 ${torso_z/2 + 0.1}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="left_upper_arm">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="right_upper_arm">
    <material>Gazebo/Green</material>
  </gazebo>

 <gazebo reference="torso">
    <material>Gazebo/Green</material>
  </gazebo>

 <gazebo reference="pelvis">
    <material>Gazebo/Blue</material>
  </gazebo>
 <gazebo reference="left_thigh">
    <material>Gazebo/Blue</material>
  </gazebo>
   <gazebo reference="right_thigh">
    <material>Gazebo/Blue</material>
  </gazebo>
</robot>